# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Lambda": "lambdasdk.ipynb"}

modules = ["lambdasdk.py"]

doc_url = "https://nic.github.io/lambdasdk/"

git_url = "https://github.com/nic/lambdasdk/tree/master/"

def custom_doc_links(name): return None
