# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"InvocationType": "lambdasdk.ipynb",
         "Lambda": "lambdasdk.ipynb"}

modules = ["lambdasdk.py"]

doc_url = "https://thanakijwanavit.github.io/lambdasdk//lambdasdk/"

git_url = "https://github.com/thanakijwanavit/lambdasdk"

def custom_doc_links(name): return None
